plugins { id 'com.android.application' }

android {
    namespace 'com.focuslock.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.focuslock.app'
        minSdk 26
        targetSdk 33
        versionCode 24
        versionName '1.0.24'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
