create table if not exists public.user_consents (
  user_id uuid not null references auth.users(id) on delete cascade,
  document_version text not null,
  platform text not null default 'android',
  app_version text not null,
  accepted_at timestamptz not null default now(),
  primary key (user_id, document_version)
);

alter table public.user_consents enable row level security;

create policy "Users read own consent" on public.user_consents
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users record own consent" on public.user_consents
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users update own consent" on public.user_consents
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

grant select, insert, update on public.user_consents to authenticated;

create table if not exists public.app_diagnostics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_code text not null check (char_length(event_code) between 1 and 80),
  event_detail text not null default '' check (char_length(event_detail) <= 180),
  app_version text not null,
  android_version text not null,
  device_model text not null,
  occurred_at timestamptz not null,
  received_at timestamptz not null default now()
);

alter table public.app_diagnostics enable row level security;

create policy "Users submit own diagnostics" on public.app_diagnostics
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Administrators read diagnostics" on public.app_diagnostics
  for select to authenticated using (public.current_user_is_admin());

grant insert, select on public.app_diagnostics to authenticated;
grant usage, select on sequence public.app_diagnostics_id_seq to authenticated;

create index if not exists app_diagnostics_user_occurred_idx
  on public.app_diagnostics(user_id, occurred_at desc);
create index if not exists app_diagnostics_received_idx
  on public.app_diagnostics(received_at desc);
create index if not exists app_remote_config_updated_by_idx
  on public.app_remote_config(updated_by);
